name: 'environment'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib>=3.2.2
  - scikit-learn>=1.0
  - pandas>=1.3.*
  - requests>=2.24.0
  - altair 
  - vega_datasets
  - graphviz
  - python-graphviz
  - jinja2
  - pip
  - sys
  - imbalanced-learn
  - pip:
    - mglearn
    - psutil>=5.7.2