name: 'environment'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - requests>=2.24.0
  - vega_datasets
  - graphviz
  - python-graphviz
  - jinja2
  - pip
  - sys
  - os
  - imbalanced-learn
  - altair>=4.1.0
  - altair-data-server>=0.4.1
  - altair-saver>= 0.5.0
  - conda>=4.11.0
  - dataframe-image>=0.1.1
  - docopt>=0.6.2
  - matplotlib>=3.4.3
  - matplotlib-inline>=0.1.2
  - numpy>=1.21.2
  - pandas>=1.3.2
  - pickleshare>=0.7.5
  - pip>=21.1.3
  - scikit-learn>=1.0
  - scipy>=1.7.1
  - selenium>=4.1.0
  - sklearn>=0.0
  - pip:
    - mglearn
    - psutil>=5.7.2

