name: 'credit_default'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - requests>=2.24.0
  - vega_datasets
  - graphviz
  - python-graphviz
  - jinja2
  - pip>=20
  - imbalanced-learn
  - altair=4.1.0
  - altair_saver
  - conda>=4.11.0
  - docopt=0.6.2
  - matplotlib=3.5.0 
  - matplotlib-inline>=0.1.2
  - numpy=1.21.2
  - pandas=1.3.3
  - pickleshare>=0.7.5
  - pip>=21.1.3
  - scikit-learn=1.0
  - scipy=1.7.1

  - pip:
    - mglearn
    - psutil
    - altair-data-server
    - selenium 
    - dataframe-image